function [eps] = defineEpochNirs(intervention, nantype)
%%
% Define the epochs used for nirs study to plot EMG checkerboard
% Arguments:
%          - intervention: boolean flag, true if it's an intervention
%            trial, false otherwise.
%          - nantype: a string or cell of strings (size = number of epochs) of
%            summary method to summarize across strides, example, nanmean or nanmedian  
% Returns:
%       -   eps: a list of epochs

if intervention
    names={'OGBase','TMBase','Adaptation5_{SS}','OGPost_{Early}','OGPost_{Late}','TMPost_{Early}',...
        'TMPost_{Late}','OGPost_{Early}-Adapt_{SS}','TMPrePosS_{La}','PosShort','OGPostPosS_{Ea}',...
        'TMPreNegS_{La}','NegShort','OGPostNegS_{Ea}','TMSlow','TMFast',...
        'Adapt1_{Late}','Adapt2_{Late}','Adapt3_{Late}','Adapt4_{Late}','Adapt5_{Late}',...
        'Adapt1_{Early}','Adapt2_{Early}','Adapt3_{Early}','Adapt4_{Early}','Adapt5_{Early}',...
        'TMPost1_{Early}','TMPost2_{Early}','TMPost3_{Early}','TMPost4_{Early}'};
    eps=defineEpochs(names,...
                    {'OGBase','TMBase','Adaptation5','OGPost','OGPost','TMPost',...
                    'TMPost','OGPost','TMTiedMid6','PosShort','OGPost2',...
                    'TMTiedMid7','NegShort','OGPost3','TMSlow','TMFast',...
                    'Adaptation1','Adaptation2','Adaptation3','Adaptation4','Adaptation5',...
                    'Adaptation1','Adaptation2','Adaptation3','Adaptation4','Adaptation5',...
                    'Post1','Post2','Post3','Post4'},...
                    [-40 -40 -40 5 -40 5 -40 5 -40  5 5 -40   5 5 -40 -40 -40 -40 -40 -40 -40 5 5 5 5 5 5 5 5 5],...
                    [0,   0,   0,1, 0, 1, 0, 1, 0,  1,1, 0,  1,1,  0   0    0   0   0   0   0 1 1 1 1 1 1 1 1 1],...
                    [5,   5,   5,0, 5, 0, 5, 0, 5,  0,0, 5,  0,0,  5,  5    5   5   5   5   5 0 0 0 0 0 0 0 0 0],...
                    nantype);
else
    names={'OGBase','TMBase','Adaptation_{SS}','OGPost_{Early}','OGPost_{Late}','TMPost_{Early}',...
        'TMPost_{Late}','OGPost_{Early}-Adapt_{SS}','TMPrePosS_{La}','PosShort','OGPostPosS_{Ea}',...
        'TMPreNegS_{La}','NegShort','OGPostNegS_{Ea}','TMSlow','TMFast'};
    eps=defineEpochs(names,...
                    {'OGBase','TMBase','Adaptation','OGPost','OGPost','TMPost',...
                    'TMPost','OGPost','TMMid2','PosShort','OGPost2',...
                    'TMMid3','NegShort','OGPost3','TMSlow','TMFast'},...
                    [-40 -40 -40 5 -40 5 -40 5 -40  5 5 -40   5 5 -40 -40],...
                    [0,   0,   0,1, 0, 1, 0, 1, 0,  1,1, 0,  1,1,  0   0],...
                    [5,   5,   5,0, 5, 0, 5, 0, 5,  0,0, 5,  0,0,  5,  5],...
                    nantype);
end